In [4]:
import numpy as np
import pandas as pd

In [6]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'Score 1' : [56,86,77,45],
        'Score 2' : [50,96,60,30]}

In [7]:
data_df = pd.DataFrame(data)
data_df.head()

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [8]:
address = ['NYC', 'NJ', 'CA', 'PA']
data_df['Address'] = address

In [9]:
data_df.head()

     Name  Height Qualification  Score 1  Score 2 Address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [13]:
# creating a new column using an old column(S)
print('Before Column Add:')
data_df.head()

Before Column Add:

     Name  Height Qualification  Score 1  Score 2 Address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [18]:
# Add column using old columns
data_df['Total Score'] = data_df['Score 1'] + data_df['Score 2']

print('After column Added:')
data_df.head()

After column Added:

,Name,Height,Qualification,Score 1,Score 2,Address,total_score,Total Score
0,Jane,5.1,Msc,56,50,NYC,106,106
1,Princi,6.2,MA,86,96,NJ,182,182
2,James,5.1,Msc,77,60,CA,137,137
3,Fadi,5.2,Msc,45,30,PA,75,75

In [19]:
data_df['Avg Score'] = data_df['Total Score'] / 2
data_df.head()

,Name,Height,Qualification,Score 1,Score 2,Address,total_score,Total Score,Avg Score
0,Jane,5.1,Msc,56,50,NYC,106,106,53.0
1,Princi,6.2,MA,86,96,NJ,182,182,91.0
2,James,5.1,Msc,77,60,CA,137,137,68.5
3,Fadi,5.2,Msc,45,30,PA,75,75,37.5

In [20]:
df2 = pd.DataFrame(data, columns=['Score 1', 'Score 2', 'Name', 'Qualification'])
print(df2)

   Score 1  Score 2    Name Qualification
0       56       50    Jane           Msc
1       86       96  Princi            MA
2       77       60   James           Msc
3       45       30    Fadi           Msc

In [21]:
values = [['Rohan', 455], ['Elvish', 250], ['John', 495],
          ['Sai', 400], ['Eric', 350], ['Adam', 450]]

In [22]:
df3 = pd.DataFrame(values, columns=['Name', 'University Marks'])

In [23]:
df3.head()

     Name  University Marks
0   Rohan               455
1  Elvish               250
2    John               495
3     Sai               400
4    Eric               350

In [25]:
df3['Percentage'] = (df3['University Marks'] / 500) * 100

In [26]:
df3.head()

     Name  University Marks  Percentage
0   Rohan               455        91.0
1  Elvish               250        50.0
2    John               495        99.0
3     Sai               400        80.0
4    Eric               350        70.0

In [ ]:
df3.insert(1, 'Age', [1000, 2000, 50, 60, 12, 20])

df3.head()

     Name   Age  University Marks  Percentage
0   Rohan  1000               455        91.0
1  Elvish  2000               250        50.0
2    John    50               495        99.0
3     Sai    60               400        80.0
4    Eric    12               350        70.0

In [29]:
df3 = df3.assign(location=['MiddleEarth', 'Moon', 'Mars', 'NYC', 'LA', 'Boston'])

In [30]:
df3.head()

     Name   Age  University Marks  Percentage     location
0   Rohan  1000               455        91.0  MiddleEarth
1  Elvish  2000               250        50.0         Moon
2    John    50               495        99.0         Mars
3     Sai    60               400        80.0          NYC
4    Eric    12               350        70.0           LA