# Pandas Basics

- Pandas is a Python library for data analysis and manipulation.
- Built on NumPy (math operations) and Matplotlib (visualization).

In [1]:
import numpy as np
import pandas as pd

In [2]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

### Pandas Datastructures
- Series - single dimensional datastructure. Similar to a list of single column (homogeneous of the same data type)
- Dataframe - multidimensional table (heterogeneous of many datatypes)

In [3]:
ser1 = pd.Series([10, 20, 30, 40], index=["A", "B", "C", "D"])
print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [4]:
# creating aseries from a preexisting dictionary
d = {
    "b": 1,
    "a": 0,
    "c": 2,
    "d": 10
}

ser2 = pd.Series(d)
ser2.iloc[3]

np.int64(10)

In [5]:
d1 = {
    "a":0.0,
    "b":1.0,
    "c":2.0
}

ser3 = pd.Series(d1)
print(ser3)

a    0.0
b    1.0
c    2.0
dtype: float64

In [6]:
calories = {
    'day1':700,
    'day2':2500,
    'day3':1200
}
# use indexes to choose certain calues for a series
ser4 = pd.Series(calories, index=('day1', 'day2'))
print(ser4)

day1     700
day2    2500
dtype: int64

In [7]:
ser5 = pd.Series(5.0, index=["a", "b", "c"])

print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

### Data Frames
- indexes (each record)
- columns (each variable)

In [8]:
fruit_data = {
    'apple_sales': [3, 2, 0, 2, 9, 4, 7, 2],
    'orange_sales': [0, 3, 2, 7, 7, 8, 3, 0 ]
}

purchases = pd.DataFrame(fruit_data, index=['Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6', 'Day7', 'Day8'])

print(purchases)

      apple_sales  orange_sales
Day1            3             0
Day2            2             3
Day3            0             2
Day4            2             7
Day5            9             7
Day6            4             8
Day7            7             3
Day8            2             0

In [9]:
rows, cols = purchases.shape
print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 8
Cols: 2

In [10]:
# to view the top number of elements, by default gives 5 elements
print(purchases.head())

      apple_sales  orange_sales
Day1            3             0
Day2            2             3
Day3            0             2
Day4            2             7
Day5            9             7

In [11]:
# to view the bottom number of elements, by default 5

print(purchases.tail())

      apple_sales  orange_sales
Day4            2             7
Day5            9             7
Day6            4             8
Day7            7             3
Day8            2             0

In [12]:
# Read employee into a pandas df
employee_df = pd.read_csv('pandasLesson_data/data/employee.csv')


employee_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [13]:
rows, cols = employee_df.shape
print('Rows:', rows)
print('Cols:', cols)

employee_df.dtypes

Rows: 15
Cols: 4

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [14]:
# Importing json data
cars_df = pd.read_json('data/cars.json')

cars_df.head()

FileNotFoundError: File data/cars.json does not exist

In [ ]:
rows, cols = cars_df.shape

In [ ]:
print('Rows:', rows)
print('Cols:', cols)

In [ ]:
cars_df.dtypes

# EDA – Exploratory Data Analysis (Step 1 of data prep)

Data Profiling
- Structure: look at the shape of the dataset
- Quality: check for missing values, duplicates, unique values
- Content: inspect data types, dispersion, and measures of central tendency

Profiling Techniques
- Data type and format validation
- Statistical summaries: descriptive stats, value counts, frequency checks
- Uniqueness and cardinality
- Pattern recognition
- Cross-validation

In [ ]:
# Getting a brief overview of descriptive statistics
cars_df.describe()

In [ ]:
# value counts of categorical data
# SBA
cars_df['city'].value_counts()

In [ ]:
cars_df['city'].unique()

In [ ]:
cars_df.info(
)

In [ ]:
cars_df.head(2)

In [ ]:
# SBA
cars_df.tail(2)

In [ ]:
# .at method to grab specific values from dataset
cars_df.at[159, "MPG"]

In [ ]:
cars_df.iat[159, 1]

In [ ]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'],
                 'Age': [20, 21, 19], 
                'Marks': [85.10, 77.80, 91.54]}

In [ ]:
# SBA
student_df = pd.DataFrame(student_dict)
student_df.head()

In [ ]:
# SBA
student_df.describe()

In [ ]:
list_index = student_df.columns

print('Column Names:', list_index)

In [ ]:
label = student_df.columns[0]

print(label)

In [ ]:
# Getting column names as a list for looping
labels_as_list = student_df.columns.to_list()

print(labels_as_list)

# EDA w/CSV

In [ ]:
e_df = pd.read_csv('data/employee.csv')

In [ ]:
e_df.head(10)

In [ ]:
e_df.tail(2)

In [ ]:
e_df.info()

In [ ]:
rows, cols = e_df.shape
print(rows, cols)

In [ ]:
e_df2 = pd.read_csv('data/employee.csv', skiprows=5, header=None)
e_df2

In [ ]:
# Get only specific columns from CSV
# e_df3 = pd.read_csv('data/employee.csv', usecols=['Name', 'Salary'])  # based on labels
e_df3 = pd.read_csv('data/employee.csv', usecols=[0, 3])  # based on index numbers
e_df3

## Selecting Columns

In [ ]:
df_cars = pd.read_json('data/cars.json')

In [ ]:
df_cars.head()

In [ ]:
# accessing single value, single brackets
df_cars.columns[0]

In [ ]:
df_cars.columns[[0,1,9]]

In [ ]:
# accessing a series using a label
df_cars['Car']

In [ ]:
df_cars[df_cars.columns[0]]

In [ ]:
# grabs subset of df with labels
df_cars[['Car', 'MPG', 'quantity']]

In [ ]:
# grabs subset of df with index numbers
df_cars[df_cars.columns[[0, 1, 9]]]

### Frequency Analysis - Value counts

In [ ]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 
                     'Electronics', 'Books', 'Books', 
                     'Clothing']}

cat_df = pd.DataFrame(data)

In [ ]:
cat_df.value_counts()

In [ ]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}

In [ ]:
sales_df = pd.DataFrame(sales_data)

In [ ]:
Frequency = sales_df['Brand'].value_counts(
)

print(Frequency)

In [ ]:
frequent_product = Frequency[Frequency > 1].index[0]

print(frequent_product)

In [ ]:
data = {'Score': [85, 92, 88, 75, None, 90, None, 85]}

In [ ]:
scores_df = pd.DataFrame(data)

In [ ]:
score_counts = scores_df.value_counts(dropna=False)
print('Score: ', score_counts)

## Converting Columns to List

In [ ]:
df = pd.read_json('data/cars.json')

In [ ]:
df.head()

In [ ]:
# Made a list of all values in the column
col_list = df['Car'].values.tolist()
print(col_list)

In [ ]:
col_numpy_arr = df['Car'].to_numpy()
print(type(col_numpy_arr))

In [ ]:
# list of df indexes
df.index.tolist()

In [ ]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}

In [ ]:
tech_df = pd.DataFrame(tech)

In [ ]:
df = tech_df.rename(columns={'Courses': 'Course Name'})

In [ ]:
tech_df.head()

# Sort using pandas

- `.sort_values()`

In [ ]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
       'Score 2' : [50,96,60,30]}

grades_df = pd.DataFrame(data)

In [ ]:
grades_df.head()

In [ ]:
grades_df = grades_df.assign(address=['NYC', 'NJ', 'CA', 'PA'])

In [ ]:
grades_df.head()

In [ ]:
print(grades_df.sort_values(by='Score 1'))

In [ ]:
print(grades_df.sort_values(by='Score 1', ascending=False))

In [ ]:
cars_df = pd.read_json("pandasLesson_data/data/cars.json")

In [ ]:
cars_df.head(15)

In [ ]:
# %%
print(cars_df.sort_values(by='quantity', ascending=True))

# %%
print(cars_df.sort_values(by=['quantity', 'Car'], ascending=[False, True]))

### Slicing a dataframe with .iloc[] & .loc[]
-   `df.loc[ row:row , colName:colName ]` - label based indexing
-   `df.iloc[row:row, [colNumber:colNumber]` - index based location

#### .iloc

In [ ]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]

In [ ]:
e_df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

e_df.head()

In [ ]:
# Grabs the first row
e_df.iloc[:1]

In [ ]:
e_df.iloc[0:4]

In [ ]:
# Grabs all rows, but only first 3 columns
e_df.iloc[:, 0:3]

In [ ]:
# Grab first 2 rows and first 2 columns

e_df.iloc[:2, :2]

#### .loc

In [ ]:
basketball = {'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]}

In [ ]:
ball = pd.DataFrame(basketball)

In [ ]:
ball.head()

In [ ]:
# Locate all rows, and colums team and rebounds

ball.loc[:, ['team', 'rebounds']]

In [ ]:
# select values from rows 3 to 6 and show the team name

ball.loc[3:6, ['team']]

### Handling Missing Values
- `df.isnull()`: to detect missing values
- `df.fillna()`: to fill missing values
- `df.dropna()`: to remove missing values
- `df.replace()`: to replace specfic values

### Pandas Date & Time
- `pd.to_datetime()`: Converts different data types into datetime object
- `pd.date_range()`: Used to generate a range of date and time
- `pd.timestamp()`: Generates the time expressed as number of seconds since 01/01/1970

In [ ]:
# Generates a range of dates from start to end. Default frequency
date_range = pd.date_range(start='07-01-2023', end='05-05-2026', periods=5)

print(date_range)

In [ ]:
date_range = pd.date_range(start='01-01-2020', end='05-05-2026', freq='QE')
date_range

In [ ]:
date_range = pd.date_range(start='01-01-2024', periods=6, tz='Asia/Tokyo')
date_range

In [ ]:
start_date = '01/01/2023'
num_days=30

date_range = pd.date_range(start=start_date, periods=num_days, freq='D')

In [ ]:
np.random.seed(42)
stock_prices = np.random.normal(loc=100, scale=5, size=num_days).round(2)

In [ ]:
stock_prices

In [ ]:
stock_df = pd.DataFrame({'Date': date_range, 'Stock Price': stock_prices})

stock_df.head()

In [ ]:
import datetime

In [ ]:
timestamp = pd.Timestamp('2026-05-05 13:38:00', tz='America/New_York')
print(timestamp)
print(type(timestamp))

In [ ]:
dt_timestamp = datetime.datetime(2026, 5, 5, 13, 38)
print(dt_timestamp)
print(type(dt_timestamp))

In [ ]:
converted_time = timestamp.tz_convert('Asia/Tokyo')
print(converted_time)

In [ ]:
timestamp.year

In [ ]:
timestamp.dayofweek

In [ ]:
dates = ['2026-05-05', '2024-01-12', '2025-10-10']
print(dates)
print(type(dates))

# dates string must all be the same format
output = pd.to_datetime(dates)
print(output)

In [35]:
input_list = ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']

print(input_list)

output = pd.to_datetime(input_list, format='mixed')
print(output)

['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
DatetimeIndex(['2023-01-01 00:00:00', '2023-01-02 00:00:00',
               '2020-03-10 14:30:45', '2023-10-13 00:00:00'],
              dtype='datetime64[us]', freq=None)

In [34]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','Eric'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '3/10/2020 143045', '13th of October, 2023']
})

In [33]:
df.dtypes

patientID                 int64
name                        str
date_of_birth    datetime64[us]
dtype: object

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 228.0 bytes

In [31]:
df['date_of_birth'].dtype

dtype('<M8[us]')

In [30]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed')
df.head()

   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-01-02
2         48  charlie    2023-01-03
3         49    keyla    2023-01-04

In [29]:
df['date_of_birth'].dtype

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [27]:
df['date_of_birth'] = df['date_of_birth'].astype('str')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patientID      4 non-null      int64
 1   name           4 non-null      str
 2   date_of_birth  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [17]:
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','keyla'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']
})

In [18]:
df['date_of_birth'] = pd.to_datetime(
    df['date_of_birth'],
    format='mixed',
    errors='coerce'
)

print('code still running after error')
print(df)

code still running after error
   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-01-02
2         48  charlie    2023-01-03
3         49    keyla    2023-01-04

In [25]:
tesla_df = pd.read_csv('pandasLesson_data/data/tesla_stock_prices.csv')
tesla_df.head()

         Date       Open   High        Low      Close  Adj Close    Volume
0  2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1  2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2  2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3  2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4  2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [26]:
tesla_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1791 entries, 0 to 1790
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1791 non-null   str
 1   Open       1791 non-null   float64
 2   High       1791 non-null   float64
 3   Low        1791 non-null   float64
 4   Close      1791 non-null   float64
 5   Adj Close  1791 non-null   float64
 6   Volume     1791 non-null   int64
dtypes: float64(5), int64(1), str(1)
memory usage: 98.1 KB

In [ ]:
# using parse_dates to change type from string into date
tesla_df = pd.read_csv('pandasLesson_data/data/tesla_stock_prices.csv', parse_dates=['Date'])

In [37]:
tesla_df.head()

        Date       Open   High        Low      Close  Adj Close    Volume
0 2010-06-29  19.000000  25.00  17.540001  23.889999  23.889999  18766300
1 2010-06-30  25.790001  30.42  23.299999  23.830000  23.830000  17187100
2 2010-07-01  25.000000  25.92  20.270000  21.959999  21.959999   8218800
3 2010-07-02  23.000000  23.10  18.709999  19.200001  19.200001   5139800
4 2010-07-06  20.000000  20.00  15.830000  16.110001  16.110001   6866900

In [45]:
# add new columns to dataframe based off of dates
tesla_df['Month'] = tesla_df['Date'].dt.month
tesla_df['Day'] = tesla_df['Date'].dt.day
tesla_df['Day Name'] = tesla_df['Date'].dt.day_name()
tesla_df['Year'] = tesla_df['Date'].dt.year
tesla_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Day,Year,Day Name
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,6,29,2010,Tuesday
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,6,30,2010,Wednesday
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,7,1,2010,Thursday
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,7,2,2010,Friday
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,7,6,2010,Tuesday
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,7,2010,Wednesday
6,2010-07-08,16.139999,17.520000,15.570000,17.459999,17.459999,7711400,7,8,2010,Thursday
7,2010-07-09,17.580000,17.900000,16.549999,17.400000,17.400000,4050600,7,9,2010,Friday
8,2010-07-12,17.950001,18.070000,17.000000,17.049999,17.049999,2202500,7,12,2010,Monday
9,2010-07-13,17.389999,18.639999,16.900000,18.139999,18.139999,2680100,7,13,2010,Tuesday

In [47]:
# grab max or min date from a dataset
least_recent = tesla_df['Date'].min()
most_recent = tesla_df['Date'].max()

print(most_recent)
print(least_recent)

2017-08-08 00:00:00
2010-06-29 00:00:00

In [ ]:
# group by month and year and sum the volume
monthly_sales = tesla_df.groupby(['Year','Month'])['Volume'].sum().reset_index()

In [53]:
monthly_sales.head(15)

    Year  Month    Volume
0   2010      6  35953400
1   2010      7  64575800
2   2010      8  15038200
3   2010      9  18045900
4   2010     10   6547800
5   2010     11  28315100
6   2010     12  36892900
7   2011      1  28420100
8   2011      2  29303500
9   2011      3  32563300
10  2011      4  29894900
11  2011      5  30348800
12  2011      6  39727300
13  2011      7  21102100
14  2011      8  27215700

#### Filter using loc[] or query[]

In [55]:
filtered_df_date = tesla_df.loc[tesla_df['Date'] >= '2010-08-01']

filtered_df_date

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Day,Year,Day Name
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100,8,2,2010,Monday
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500,8,3,2010,Tuesday
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000,8,4,2010,Wednesday
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200,8,5,2010,Thursday
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900,8,6,2010,Friday
...,...,...,...,...,...,...,...,...,...,...,...
1786,2017-08-02,318.940002,327.119995,311.220001,325.890015,325.890015,13091500,8,2,2017,Wednesday
1787,2017-08-03,345.329987,350.000000,343.149994,347.089996,347.089996,13535000,8,3,2017,Thursday
1788,2017-08-04,347.000000,357.269989,343.299988,356.910004,356.910004,9198400,8,4,2017,Friday
1789,2017-08-07,357.350006,359.480011,352.750000,355.170013,355.170013,6276900,8,7,2017,Monday
1790,2017-08-08,357.529999,368.579987,357.399994,365.220001,365.220001,7449837,8,8,2017,Tuesday

In [56]:
filtered_df_date = tesla_df.loc[(tesla_df['Date'] >= '2010-08-01') & (tesla_df['Date'] <= '2010-12-31')]
 
filtered_df_date

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Day,Year,Day Name
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100,8,2,2010,Monday
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500,8,3,2010,Tuesday
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000,8,4,2010,Wednesday
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200,8,5,2010,Thursday
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900,8,6,2010,Friday
...,...,...,...,...,...,...,...,...,...,...,...
125,2010-12-27,28.020000,28.580000,25.059999,25.549999,25.549999,9301900,12,27,2010,Monday
126,2010-12-28,25.850000,26.750000,25.000000,26.410000,26.410000,4056300,12,28,2010,Tuesday
127,2010-12-29,27.030001,28.010000,26.500000,27.730000,27.730000,3319200,12,29,2010,Wednesday
128,2010-12-30,27.700001,27.900000,26.379999,26.500000,26.500000,2041100,12,30,2010,Thursday
129,2010-12-31,26.570000,27.250000,26.500000,26.629999,26.629999,1417900,12,31,2010,Friday

In [58]:
filtered_df = tesla_df.query("Date >= '2010-08-01' and Date <= '2010-12-01'")
filtered_df

,Date,Open,High,Low,Close,Adj Close,Volume,Month,Day,Year,Day Name
23,2010-08-02,20.500000,20.969999,20.330000,20.920000,20.920000,718100,8,2,2010,Monday
24,2010-08-03,21.000000,21.950001,20.820000,21.950001,21.950001,1230500,8,3,2010,Tuesday
25,2010-08-04,21.950001,22.180000,20.850000,21.260000,21.260000,913000,8,4,2010,Wednesday
26,2010-08-05,21.540001,21.549999,20.049999,20.450001,20.450001,796200,8,5,2010,Thursday
27,2010-08-06,20.100000,20.160000,19.520000,19.590000,19.590000,741900,8,6,2010,Friday
...,...,...,...,...,...,...,...,...,...,...,...
104,2010-11-24,35.270000,35.970001,34.330002,35.470001,35.470001,1425000,11,24,2010,Wednesday
105,2010-11-26,35.599998,36.000000,34.750000,35.320000,35.320000,350600,11,26,2010,Friday
106,2010-11-29,35.410000,35.950001,33.330002,34.330002,34.330002,1145600,11,29,2010,Monday
107,2010-11-30,33.740002,35.330002,33.410000,35.330002,35.330002,2222600,11,30,2010,Tuesday
108,2010-12-01,35.869999,36.419998,33.450001,34.349998,34.349998,1299200,12,1,2010,Wednesday