# Pandas Basics

- Pandas is a Python library for data analysis and manipulation.
- Built on NumPy (math operations) and Matplotlib (visualization).

In [34]:
import numpy as np
import pandas as pd

In [35]:
print(f'Pandas: {pd.__version__}')
print(f'Numpy: {np.__version__}')

Pandas: 3.0.2
Numpy: 2.4.4

### Pandas Datastructures
- Series - single dimensional datastructure. Similar to a list of single column (homogeneous of the same data type)
- Dataframe - multidimensional table (heterogeneous of many datatypes)

In [36]:
ser1 = pd.Series([10, 20, 30, 40], index=["A", "B", "C", "D"])
print(ser1)

A    10
B    20
C    30
D    40
dtype: int64

In [37]:
# creating aseries from a preexisting dictionary
d = {
    "b": 1,
    "a": 0,
    "c": 2,
    "d": 10
}

ser2 = pd.Series(d)
ser2.iloc[3]

np.int64(10)

In [38]:
d1 = {
    "a":0.0,
    "b":1.0,
    "c":2.0
}

ser3 = pd.Series(d1)
print(ser3)

a    0.0
b    1.0
c    2.0
dtype: float64

In [39]:
calories = {
    'day1':700,
    'day2':2500,
    'day3':1200
}
# use indexes to choose certain calues for a series
ser4 = pd.Series(calories, index=('day1', 'day2'))
print(ser4)

day1     700
day2    2500
dtype: int64

In [40]:
ser5 = pd.Series(5.0, index=["a", "b", "c"])

print(ser5)

a    5.0
b    5.0
c    5.0
dtype: float64

### Data Frames
- indexes (each record)
- columns (each variable)

In [41]:
fruit_data = {
    'apple_sales': [3, 2, 0, 2, 9, 4, 7, 2],
    'orange_sales': [0, 3, 2, 7, 7, 8, 3, 0 ]
}

purchases = pd.DataFrame(fruit_data, index=['Day1', 'Day2', 'Day3', 'Day4', 'Day5', 'Day6', 'Day7', 'Day8'])

print(purchases)

      apple_sales  orange_sales
Day1            3             0
Day2            2             3
Day3            0             2
Day4            2             7
Day5            9             7
Day6            4             8
Day7            7             3
Day8            2             0

In [42]:
rows, cols = purchases.shape
print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 8
Cols: 2

In [43]:
# to view the top number of elements, by default gives 5 elements
print(purchases.head())

      apple_sales  orange_sales
Day1            3             0
Day2            2             3
Day3            0             2
Day4            2             7
Day5            9             7

In [44]:
# to view the bottom number of elements, by default 5

print(purchases.tail())

      apple_sales  orange_sales
Day4            2             7
Day5            9             7
Day6            4             8
Day7            7             3
Day8            2             0

In [50]:
# Read employee into a pandas df
employee_df = pd.read_csv('pandasLesson_data/data/employee.csv')


employee_df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [ ]:
rows, cols = employee_df.shape
print('Rows:', rows)
print('Cols:', cols)

employee_df.dtypes

Rows: 15
Cols: 4

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [ ]:
# Importing json data
cars_df = pd.read_json('data/cars.json')

cars_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [ ]:
rows, cols = cars_df.shape

In [ ]:
print('Rows:', rows)
print('Cols:', cols)

Rows: 161
Cols: 11

In [ ]:
cars_df.dtypes

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

# EDA – Exploratory Data Analysis (Step 1 of data prep)

Data Profiling
- Structure: look at the shape of the dataset
- Quality: check for missing values, duplicates, unique values
- Content: inspect data types, dispersion, and measures of central tendency

Profiling Techniques
- Data type and format validation
- Statistical summaries: descriptive stats, value counts, frequency checks
- Uniqueness and cardinality
- Pattern recognition
- Cross-validation

In [ ]:
# Getting a brief overview of descriptive statistics
cars_df.describe()

,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,quantity
count,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000,161.000000
mean,23.801863,5.347826,185.232919,100.664596,2915.093168,15.509938,76.260870,224.875776
std,8.810125,1.761607,105.394809,41.079640,890.293883,2.515780,3.818576,127.741084
min,0.000000,3.000000,68.000000,0.000000,1613.000000,8.000000,70.000000,5.000000
25%,17.000000,4.000000,98.000000,72.000000,2130.000000,14.000000,73.000000,112.000000
50%,24.000000,4.000000,140.000000,88.000000,2625.000000,15.500000,76.000000,227.000000
75%,31.000000,8.000000,302.000000,130.000000,3620.000000,17.100000,80.000000,337.000000
max,46.600000,8.000000,440.000000,215.000000,4955.000000,22.100000,82.000000,439.000000

In [ ]:
# value counts of categorical data
# SBA
cars_df['city'].value_counts()

city
NewYork    36
NJ         35
DALLAS     33
TEXAS      30
OH         27
Name: count, dtype: int64

In [ ]:
cars_df['city'].unique()

<StringArray>
['NJ', 'DALLAS', 'TEXAS', 'OH', 'NewYork']
Length: 5, dtype: str

In [ ]:
cars_df.info(
)

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           161 non-null    str
 1   MPG           161 non-null    float64
 2   Cylinders     161 non-null    int64
 3   Displacement  161 non-null    float64
 4   Horsepower    161 non-null    int64
 5   Weight        161 non-null    int64
 6   Acceleration  161 non-null    float64
 7   Model         161 non-null    int64
 8   Origin        161 non-null    str
 9   quantity      161 non-null    int64
 10  city          161 non-null    str
dtypes: float64(3), int64(5), str(3)
memory usage: 14.0 KB

In [ ]:
cars_df.head(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS

In [ ]:
# SBA
cars_df.tail(2)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH

In [ ]:
# .at method to grab specific values from dataset
cars_df.at[159, "MPG"]

np.float64(36.0)

In [ ]:
cars_df.iat[159, 1]

np.float64(36.0)

In [ ]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'],
                 'Age': [20, 21, 19], 
                'Marks': [85.10, 77.80, 91.54]}

In [ ]:
# SBA
student_df = pd.DataFrame(student_dict)
student_df.head()

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

In [ ]:
# SBA
student_df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [ ]:
list_index = student_df.columns

print('Column Names:', list_index)

Column Names: Index(['Name', 'Age', 'Marks'], dtype='str')

In [ ]:
label = student_df.columns[0]

print(label)

Name

In [ ]:
# Getting column names as a list for looping
labels_as_list = student_df.columns.to_list()

print(labels_as_list)

['Name', 'Age', 'Marks']

# EDA w/CSV

In [ ]:
e_df = pd.read_csv('data/employee.csv')

In [ ]:
e_df.head(10)

       Name   Age  Weight     Salary
0     James  36.0    75.0  5428000.0
1   Villers  38.0    74.0  3428000.0
2     VKole  31.0    70.0  8428000.0
3     Smith  34.0    80.0  4428000.0
4     Gayle  40.0   100.0  4528000.0
5      Adam  40.0     NaN  4528000.0
6    Rooter  33.0    72.0  7028000.0
7  Peterson  42.0    85.0  2528000.0
8     lynda  42.0    85.0        NaN
9       NaN  42.0    85.0        NaN

In [ ]:
e_df.tail(2)

    Name   Age  Weight     Salary
13  John  41.0    85.0  1528000.0
14   Ali  26.0    69.0        NaN

In [ ]:
e_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), str(1)
memory usage: 612.0 bytes

In [ ]:
rows, cols = e_df.shape
print(rows, cols)

15 4

In [ ]:
e_df2 = pd.read_csv('data/employee.csv', skiprows=5, header=None)
e_df2

           0     1      2          3
0      Gayle  40.0  100.0  4528000.0
1       Adam  40.0    NaN  4528000.0
2     Rooter  33.0   72.0  7028000.0
3   Peterson  42.0   85.0  2528000.0
4      lynda  42.0   85.0        NaN
5        NaN  42.0   85.0        NaN
6      Jenny   NaN  100.0    25632.0
7       Kenn   NaN  110.0    25632.0
8        Aly   NaN   90.0    25582.0
9       John  41.0   85.0  1528000.0
10       Ali  26.0   69.0        NaN

In [ ]:
# Get only specific columns from CSV
# e_df3 = pd.read_csv('data/employee.csv', usecols=['Name', 'Salary'])  # based on labels
e_df3 = pd.read_csv('data/employee.csv', usecols=[0, 3])  # based on index numbers
e_df3

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

## Selecting Columns

In [ ]:
df_cars = pd.read_json('data/cars.json')

In [ ]:
df_cars.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [ ]:
# accessing single value, single brackets
df_cars.columns[0]

'Car'

In [ ]:
df_cars.columns[[0,1,9]]

Index(['Car', 'MPG', 'quantity'], dtype='str')

In [ ]:
# accessing a series using a label
df_cars['Car']

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [ ]:
df_cars[df_cars.columns[0]]

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [ ]:
# grabs subset of df with labels
df_cars[['Car', 'MPG', 'quantity']]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

In [ ]:
# grabs subset of df with index numbers
df_cars[df_cars.columns[[0, 1, 9]]]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

### Frequency Analysis - Value counts

In [ ]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 
                     'Electronics', 'Books', 'Books', 
                     'Clothing']}

cat_df = pd.DataFrame(data)

In [ ]:
cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [ ]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
           'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
           'Sales':[1000,2000,4000,2000,1000,4000],
           'Profit':[500,1000,1000,1500,1000,1500],
           'Pices left':[5000,4000,4000,5000,5000,1000]}

In [ ]:
sales_df = pd.DataFrame(sales_data)

In [ ]:
Frequency = sales_df['Brand'].value_counts(
)

print(Frequency)

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64

In [ ]:
frequent_product = Frequency[Frequency > 1].index[0]

print(frequent_product)

Samsung

In [ ]:
data = {'Score': [85, 92, 88, 75, None, 90, None, 85]}

In [ ]:
scores_df = pd.DataFrame(data)

In [ ]:
score_counts = scores_df.value_counts(dropna=False)
print('Score: ', score_counts)

Score:  Score
85.0     2
NaN      2
92.0     1
88.0     1
75.0     1
90.0     1
Name: count, dtype: int64

## Converting Columns to List

In [ ]:
df = pd.read_json('data/cars.json')

In [ ]:
df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [ ]:
# Made a list of all values in the column
col_list = df['Car'].values.tolist()
print(col_list)

['Chevrolet Vega', 'Chevrolet Vega (sw)', 'Chevrolet Vega 2300', 'Chevrolet Woody', 'Chevrolete Chevelle Malibu', 'Chevy C20', 'Chevy S-10', 'Chrysler Cordoba', 'Chrysler Lebaron Medallion', 'Chrysler Lebaron Salon', 'Chrysler Lebaron Town @ Country (sw)', 'Chrysler New Yorker Brougham', 'Chrysler Newport Royal', 'Citroen DS-21 Pallas', 'Datsun 1200', 'Datsun 200SX', 'Datsun 200-SX', 'Datsun 210', 'Datsun 210', 'Datsun 210 MPG', 'Datsun 280-ZX', 'Datsun 310', 'Datsun 310 GX', 'Datsun 510', 'Datsun 510 (sw)', 'Datsun 510 Hatchback', 'Datsun 610', 'Datsun 710', 'Datsun 710', 'Datsun 810', 'Datsun 810 Maxima', 'Datsun B210', 'Datsun B-210', 'Datsun B210 GX', 'Datsun F-10 Hatchback', 'Datsun PL510', 'Datsun PL510', 'Dodge Aries SE', 'Dodge Aries Wagon (sw)', 'Dodge Aspen', 'Dodge Aspen', 'Dodge Aspen 6', 'Dodge Aspen SE', 'Dodge Challenger SE', 'Dodge Charger 2.2', 'Dodge Colt', 'Dodge Colt', 'Dodge Colt', 'Dodge Colt (sw)', 'Dodge Colt Hardtop', 'Dodge Colt Hatchback Custom', 'Dodge Colt m/m', 'Dodge Coronet Brougham', 'Dodge Coronet Custom', 'Dodge Coronet Custom (sw)', 'Dodge D100', 'Dodge D200', 'Dodge Dart Custom', 'Dodge Diplomat', 'Dodge Magnum XE', 'Dodge Monaco (sw)', 'Dodge Monaco Brougham', 'Dodge Omni', 'Dodge Rampage', 'Dodge St. Regis', 'Fiat 124 Sport Coupe', 'Fiat 124 TC', 'Fiat 124B', 'Fiat 128', 'Fiat 128', 'Fiat 131', 'Fiat Strada Custom', 'Fiat x1.9', 'Ford Country', 'Ford Country Squire (sw)', 'Ford Country Squire (sw)', 'Ford Escort 2H', 'Ford Escort 4W', 'Ford F108', 'Ford F250', 'Ford Fairmont', 'Ford Fairmont (auto)', 'Ford Fairmont (man)', 'Ford Fairmont 4', 'Ford Fairmont Futura', 'Ford Fiesta', 'Ford Futura', 'Ford Galaxie 500', 'Ford Galaxie 500', 'Ford Galaxie 500', 'Ford Gran Torino', 'Ford Gran Torino', 'Ford Gran Torino', 'Ford Gran Torino (sw)', 'Ford Gran Torino (sw)', 'Ford Grenada', 'Ford Grenada ghia', 'Ford Grenada gl', 'Ford Grenada l', 'Ford LTD', 'Ford LTD', 'Ford LTD Landau', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Maverick', 'Ford Mustang', 'Ford Mustang Boss 302', 'Ford Mustang Cobra', 'Ford Mustang GL', 'Ford Mustang II', 'Ford Mustang II 2+2', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto', 'Ford Pinto (sw)', 'Ford Pinto Runabout', 'Ford Ranger', 'Ford Thunderbird', 'Ford Torino', 'Ford Torino (sw)', 'Ford Torino 500', 'Hi 1200D', 'Honda Accord', 'Honda Accord', 'Honda Accord CVCC', 'Honda Accord LX', 'Honda Civic', 'Honda Civic', 'Honda Civic', 'Honda Civic (auto)', 'Honda Civic 1300', 'Honda Civic 1500 gl', 'Honda Civic CVCC', 'Honda Civic CVCC', 'Honda Prelude', 'Mazda 626', 'Mazda 626', 'Mazda GLC', 'Mazda GLC 4', 'Mazda GLC Custom', 'Mazda GLC Custom l', 'Mazda GLC Deluxe', 'Mazda GLC Deluxe', 'Mazda RX2 Coupe', 'Mazda RX3', 'Mazda RX-4', 'Mazda RX-7 GS', 'Mercedes Benz 300d', 'Mercedes-Benz 240d', 'Mercedes-Benz 280s', 'Mercury Capri 2000', 'Mercury Capri v6', 'Mercury Cougar Brougham', 'Mercury Grand Marquis', 'Mercury Lynx l', 'Mercury Marquis']

In [ ]:
col_numpy_arr = df['Car'].to_numpy()
print(type(col_numpy_arr))

<class 'numpy.ndarray'>

In [ ]:
# list of df indexes
df.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160]

In [ ]:
tech = {
    'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
    'Fee': [100, 2000, 250, 300],
    'Duration':['40days', '50days', '3 months', '1 year']
}

In [ ]:
tech_df = pd.DataFrame(tech)

In [ ]:
df = tech_df.rename(columns={'Courses': 'Course Name'})

In [ ]:
tech_df.head()

            Courses   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year

# Sort using pandas

- `.sort_values()`

In [ ]:
data = {'Name': ['Jane', 'Princi', 'James', 'Fadi'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
       'Score 1' : [56,86,77,45],
       'Score 2' : [50,96,60,30]}

grades_df = pd.DataFrame(data)

In [ ]:
grades_df.head()

     Name  Height Qualification  Score 1  Score 2
0    Jane     5.1           Msc       56       50
1  Princi     6.2            MA       86       96
2   James     5.1           Msc       77       60
3    Fadi     5.2           Msc       45       30

In [ ]:
grades_df = grades_df.assign(address=['NYC', 'NJ', 'CA', 'PA'])

In [ ]:
grades_df.head()

     Name  Height Qualification  Score 1  Score 2 address
0    Jane     5.1           Msc       56       50     NYC
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
3    Fadi     5.2           Msc       45       30      PA

In [ ]:
print(grades_df.sort_values(by='Score 1'))

     Name  Height Qualification  Score 1  Score 2 address
3    Fadi     5.2           Msc       45       30      PA
0    Jane     5.1           Msc       56       50     NYC
2   James     5.1           Msc       77       60      CA
1  Princi     6.2            MA       86       96      NJ

In [ ]:
print(grades_df.sort_values(by='Score 1', ascending=False))

     Name  Height Qualification  Score 1  Score 2 address
1  Princi     6.2            MA       86       96      NJ
2   James     5.1           Msc       77       60      CA
0    Jane     5.1           Msc       56       50     NYC
3    Fadi     5.2           Msc       45       30      PA

In [49]:
cars_df = pd.read_json("pandasLesson_data/data/cars.json")

In [51]:
cars_df.head(15)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork
5,Chevy C20,10.0,8,307.0,200,4376,15.0,70,US,70,NJ
6,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US,7,NewYork
7,Chrysler Cordoba,15.5,8,400.0,190,4325,12.2,77,US,7,NJ
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
9,Chrysler Lebaron Salon,17.6,6,225.0,85,3465,16.6,81,US,412,TEXAS
10,Chrysler Lebaron Town @ Country (sw),18.5,8,360.0,150,3940,13.0,79,US,337,OH
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork
12,Chrysler Newport Royal,13.0,8,400.0,190,4422,12.5,72,US,115,NJ
13,Citroen DS-21 Pallas,0.0,4,133.0,115,3090,17.5,70,Europe,58,DALLAS
14,Datsun 1200,35.0,4,72.0,69,1613,18.0,71,Japan,99,TEXAS

In [53]:
# %%
print(cars_df.sort_values(by='quantity', ascending=True))

# %%
print(cars_df.sort_values(by=['quantity', 'Car'], ascending=[False, True]))

                            Car   MPG  Cylinders  Displacement  Horsepower  \
112         Ford Mustang II 2+2  25.5          4         140.0          89
123                 Ford Torino  17.0          8         302.0         140
6                    Chevy S-10  31.0          4         119.0          82
7              Chrysler Cordoba  15.5          8         400.0         190
121                 Ford Ranger  28.0          4         120.0          79
..                          ...   ...        ...           ...         ...
128                Honda Accord  36.0          4         107.0          75
134          Honda Civic (auto)  32.0          4          91.0          67
22                Datsun 310 GX  38.0          4          91.0          67
8    Chrysler Lebaron Medallion  26.0          4         156.0          92
110             Ford Mustang GL  27.0          4         140.0          86

     Weight  Acceleration  Model Origin  quantity     city
112    2755          15.8     77     US         5       NJ
123    3449          10.5     70     US         5       OH
6      2720          19.4     82     US         7  NewYork
7      4325          12.2     77     US         7       NJ
121    2625          18.6     82     US         7   DALLAS
..      ...           ...    ...    ...       ...      ...
128    2205          14.5     82  Japan       427       OH
134    1965          15.7     82  Japan       430    TEXAS
22     1995          16.2     82  Japan       431       NJ
8      2585          14.5     82     US       434   DALLAS
110    2790          15.6     82     US       439       OH

[161 rows x 11 columns]
                            Car   MPG  Cylinders  Displacement  Horsepower  \
110             Ford Mustang GL  27.0          4         140.0          86
8    Chrysler Lebaron Medallion  26.0          4         156.0          92
22                Datsun 310 GX  38.0          4          91.0          67
134          Honda Civic (auto)  32.0          4          91.0          67
128                Honda Accord  36.0          4         107.0          75
..                          ...   ...        ...           ...         ...
121                 Ford Ranger  28.0          4         120.0          79
130             Honda Accord LX  29.5          4          98.0          68
147            Mazda GLC Deluxe  34.1          4          86.0          65
112         Ford Mustang II 2+2  25.5          4         140.0          89
123                 Ford Torino  17.0          8         302.0         140

     Weight  Acceleration  Model Origin  quantity    city
110    2790          15.6     82     US       439      OH
8      2585          14.5     82     US       434  DALLAS
22     1995          16.2     82  Japan       431      NJ
134    1965          15.7     82  Japan       430   TEXAS
128    2205          14.5     82  Japan       427      OH
..      ...           ...    ...    ...       ...     ...
121    2625          18.6     82     US         7  DALLAS
130    2135          16.6     78  Japan         7      NJ
147    1975          15.2     79  Japan         7      NJ
112    2755          15.8     77     US         5      NJ
123    3449          10.5     70     US         5      OH

[161 rows x 11 columns]

### Slicing a dataframe with .iloc[] & .loc[]
-   `df.loc[ row:row , colName:colName ]` - label based indexing
-   `df.iloc[row:row, [colNumber:colNumber]` - index based location

#### .iloc

In [55]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]

In [56]:
e_df = pd.DataFrame(employee_list, columns=['Name', 'Age', 'Weight', 'Salary'])

e_df.head()

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000
4    Gayle   40     100  4528000

In [ ]:
# Grabs the first row
e_df.iloc[:1]

    Name  Age  Weight   Salary
0  James   36      75  5428000

In [61]:
e_df.iloc[0:4]

      Name  Age  Weight   Salary
0    James   36      75  5428000
1  Villers   38      74  3428000
2    VKole   31      70  8428000
3    Smith   34      80  4428000

In [65]:
# Grabs all rows, but only first 3 columns
e_df.iloc[:, 0:3]

       Name  Age  Weight
0     James   36      75
1   Villers   38      74
2     VKole   31      70
3     Smith   34      80
4     Gayle   40     100
5    Rooter   33      72
6  Peterson   42      85
7      John   41      85

In [67]:
# Grab first 2 rows and first 2 columns

e_df.iloc[:2, :2]

      Name  Age
0    James   36
1  Villers   38

#### .loc

In [68]:
basketball = {'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]}

In [69]:
ball = pd.DataFrame(basketball)

In [70]:
ball.head()

  team  points  assists  rebounds  steals  blocks
0    A      18        5        11       4       1
1    B      22        7         8       3       0
2    C      19        7        10       3       0
3    D      14        9         6       2       3
4    E      14       12         6       5       2

In [ ]:
# Locate all rows, and colums team and rebounds

ball.loc[:, ['team', 'rebounds']]

  team  rebounds
0    A        11
1    B         8
2    C        10
3    D         6
4    E         6
5    F         5
6    G         9
7    H        12

In [74]:
# select values from rows 3 to 6 and show the team name

ball.loc[3:6, ['team']]

  team
3    D
4    E
5    F
6    G

### Handling Missing Values
- `df.isnull()`: to detect missing values
- `df.fillna()`: to fill missing values
- `df.dropna()`: to remove missing values
- `df.replace()`: to replace specfic values